### ISSUE TITLE
Occasional duplicate calls to update ddns

### ISSUE THREAD

**Issue by bengalih** [ulygit/asus_rt_ac68u#21] opened 2023-04-07 15:11 UTC
Hey - haven't been here in a while!  Script has for the most part been running fine so not much need to revisit.
Are you still using it?

I noticed a problem on my RT-AC68U that I'm wondering if you've seen anything like it?
My ISP is apparently sending me a lease time of only 1 hour on my IPv6 lease which causes a refresh every 30 minutes.
Even though I don't update IPv6 via ddns, this still triggers a custom ddns event on the router.
Normally, this wouldn't be an issue as running the script once every 30 minutes shouldn't be a problem at all (i.e. still well under any limits to update the record with an API call once every 30 minutes).

But if you take a look at my logs you will see something like this:

`2023-04-06 12:13:19	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 12:43:19	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 13:13:19	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 13:43:19	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 14:13:19	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 14:43:20	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 15:13:20	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 15:43:20	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 15:43:22	UPDATE_THROTTLED	
2023-04-06 15:43:52	UPDATE_THROTTLED	
2023-04-06 15:44:22	UPDATE_THROTTLED	
2023-04-06 15:44:52	UPDATE_THROTTLED	
2023-04-06 15:45:22	UPDATE_THROTTLED	
2023-04-06 15:45:52	UPDATE_THROTTLED	
2023-04-06 15:46:22	UPDATE_THROTTLED	
2023-04-06 15:46:52	UPDATE_THROTTLED	
2023-04-06 15:47:22	UPDATE_THROTTLED	
2023-04-06 15:47:52	UPDATE_THROTTLED	
2023-04-06 15:48:23	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 16:13:20	UPDATE_SUCCESS	{"result":{"id":REDACTED}
2023-04-06 16:43:21	UPDATE_SUCCESS	{"result":{"id":REDACTED}
`
So what you are seeing is that **_most_** of the time everything is going fine every 30 mins.  But occasionally you get what you see at the 15:43:20 timestamp.  Namely that the update succeeds, but then the script is run again multiple times and keeps failing due to the throttling (since it was just properly updated).  This continues for the 300 seconds of throttle until what you get at the 15:48:23 timestamp when it finally succeeds again.
Then you see it continues on normally working every 30 minutes.

This isn't a failure of the script, but rather something funky happening on the merlin.    This is what the normal syslog entries look like when it updates properly just the once:

`Apr  6 15:13:18 rc_service: dhcp6c 23328:notify_rc restart_ddns
Apr  6 15:13:18 custom_script: Running /jffs/scripts/service-event (args: restart ddns)
Apr  6 15:13:18 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:13:18 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:13:20 ddns: Completed custom ddns update
Apr  6 15:13:20 custom_script: Running /jffs/scripts/service-event-end (args: restart ddns)`

But when it fails it looks like this:

`Apr  6 15:43:18 rc_service: dhcp6c 28346:notify_rc restart_ddns
Apr  6 15:43:18 custom_script: Running /jffs/scripts/service-event (args: restart ddns)
Apr  6 15:43:19 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:43:19 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:43:20 watchdog: start ddns.
Apr  6 15:43:20 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:43:20 rc_service: waitting "restart_ddns" via  ...
Apr  6 15:43:20 ddns: Completed custom ddns update
Apr  6 15:43:20 custom_script: Running /jffs/scripts/service-event-end (args: restart ddns)
Apr  6 15:43:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:43:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:43:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:43:22 ddns: Custom ddns update failed
Apr  6 15:43:22 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:43:51 watchdog: start ddns.
Apr  6 15:43:51 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:43:51 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:43:52 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:43:52 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:43:52 ddns: Custom ddns update failed
Apr  6 15:43:52 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:44:21 watchdog: start ddns.
Apr  6 15:44:21 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:44:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:44:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:44:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:44:22 ddns: Custom ddns update failed
Apr  6 15:44:22 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:44:51 watchdog: start ddns.
Apr  6 15:44:51 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:44:51 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:44:52 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:44:52 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:44:52 ddns: Custom ddns update failed
Apr  6 15:44:52 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:45:21 watchdog: start ddns.
Apr  6 15:45:21 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:45:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:45:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:45:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:45:22 ddns: Custom ddns update failed
Apr  6 15:45:22 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:45:51 watchdog: start ddns.
Apr  6 15:45:51 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:45:51 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:45:52 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:45:52 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:45:52 ddns: Custom ddns update failed
Apr  6 15:45:52 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:46:21 watchdog: start ddns.
Apr  6 15:46:21 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:46:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:46:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:46:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:46:22 ddns: Custom ddns update failed
Apr  6 15:46:22 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:46:51 watchdog: start ddns.
Apr  6 15:46:51 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:46:51 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:46:52 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:46:52 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:46:52 ddns: Custom ddns update failed
Apr  6 15:46:52 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:47:21 watchdog: start ddns.
Apr  6 15:47:21 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:47:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:47:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:47:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:47:22 ddns: Custom ddns update failed
Apr  6 15:47:22 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:47:51 watchdog: start ddns.
Apr  6 15:47:51 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:47:51 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:47:52 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:47:52 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:47:52 ddns: Custom ddns update failed
Apr  6 15:47:52 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)
Apr  6 15:48:21 watchdog: start ddns.
Apr  6 15:48:21 rc_service: watchdog 396:notify_rc start_ddns
Apr  6 15:48:21 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Apr  6 15:48:22 start_ddns: update CUSTOM , wan_unit 0
Apr  6 15:48:22 custom_script: Running /jffs/scripts/ddns-start (args: XX.XX.XX.XX)
Apr  6 15:48:23 ddns: Completed custom ddns update
Apr  6 15:48:23 custom_script: Running /jffs/scripts/service-event-end (args: start ddns)`

There is that "watchdog" line near the top of the problematic set.  I'm not exactly sure what is happening but it is like this watchdog is jumping in and doing another restart right after the normal update is triggered causing this throttle loop.

I know this isn't a direct script issue, but I'm thinking about ways to mitigate this.  Maybe there is something malfunctioning on my device, but I can't see what that is.   I posted over in the merlin forums (no good feedback yet), but because those using this script are more likely to be paying attention to these matters I wanted to bring it up here to see if there were any ideas?

**Comment by ulygit** [comment] 2023-04-07 18:20
Hey @bengalih, happy to hear you're still using the script. The easiest mitigation the script can readily accommodate is to lower the throttling threshold (down from 300 seconds). The current version of the script sets it to 5 seconds because, as you observed, Merlin retries the ddns update every 30 seconds when a failure to update occurs. I recall that 5 seconds was comfortably within the Cloudflare TOS. You should confirm the TOS yourself, but I believe you could lower it further down to 1 or 2 seconds to simply accommodate the "funky" Merlin behavior.

I suspect the problem is occurring because of competing monitoring code in Merlin. Changes to DNS trigger a ddns update, which may cause the ddns service to restart. Separately, the watchdog is monitoring the status of the ddns service and observes that it is stopped (because of the restart) and tries to start it up again.

**Comment by bengalih** [comment] 2023-04-07 22:03
Yeah, lowering the threshold was a consideration I had.  TBH, I'm not really sure why the threshold was ever set so high to begin with, or even implemented.  The API limits seem fairly generous and I'm not sure how you would bypass them while using the script.

Even if Merlin tried to run the script repeatedly, it unlikely would get more than a few runs off every second which would seem to be well under the API limits?  I suppose if you were manually executing the script and there was a problem with a loop, but wouldn't just the network delays in trying to query/set the value be enough to make the limits moot?

Your synopsis of root cause is possibly correct, although I don't see anything in the logs that indicates that the ddns script triggers are happening because dns is being restarted.  There doesn't seem to be a consistent pattern to the times where it misbehaves.  I might have 12-15 good updates in a row, then one that loops, then another 2 normal ones, then another loop.  Over the course of a day it might happen 3-6 times.

I am hoping to understand "why" it is happening as much as I am trying to work around it with something like lowering the throttle, but so far I haven't been able to find anything in the logging that would indicate the root cause.

Someone also pointed me to https://www.dnsomatic.com/ which may not have been around when you first wrote the script.  It appears that they are listed as one of the custom options in the Merlin client now.  On the one hand, I'm not sure I want to depend on another 3rd party service to proxy the data (since it is another point of failure), but OTOH it does reduce complexity by utilizing a built-in supported function rather than a 3rd party script.

I may set it up just for the experience and then also to monitor the ddns events under that and see if I continue to get "double events".  

thanks.

**Comment by bengalih** [comment] 2023-04-08 00:05
Whelp, I tried the DNS-O-Matic and it is a no-go for Cloudflare.
It works, but only supports the Global API key and not the zone API structure that we updated the script for.
So, it's useless as providing the Global API key is not an option due to security reasons.

So, I've just updated to the latest version of the script with the 5 second throttle and at least if I have the double event it will only cycle through once.

**Comment by ulygit** [comment] 2023-04-08 05:14
Glad you're reasonably sorted now. It's tough to recall, but the throttling threshold was probably set to 5 minutes because that seemed reasonable for DNS updates in typical scenarios, and atypical users (I won't name names) can always adjust.

Regarding the watchdog, I should've clarified that I suspect the problem is a timing bug or some other similar "irregular state" bug. The watchdog isn't triggered by the restart directly. It's probably checking every few seconds to see if the ddns service is up (or some other ddns-related check) and it occasionally just happens to check precisely when the ddns service is being restarted. I'm not surprised it's inconsistent.

Looking at your logs, it appears the "correct" update is characterized by the string "args: restart ddns". That's triggered by the dhcp service and is expected whenever your lease is renewed. The "problem" update happens right after, and it's characterized by the string "args: start ddns". That's triggered by the watchdog, which, judging by the "start," seems to think that the ddns service isn't running and needs to be started rather than restarted.

In my own script logs, I see similar duplicated, seemingly-superfluous ddns updates, but they're minutes apart rather than seconds apart as in your case. They also occur maybe once a month rather than multiple times daily. The system logs don't show anything similar either, though it looks like you're running at a finer logging level than I am.

**Comment by bengalih** [comment] 2023-04-08 17:21
So when the issue came up I had an idea.  I didn't mention at first here because I though it at first maybe counterintuitive to your reasoning for creating the throttle in the first place.

I thought (to minimize the loop, not solve the rogue watchdog...which I'm not sure can be done):  What if instead of issuing a failure on a Throttle event, we first see if the IP even *needs* updating?  Why don't we query the CF record first and if the IP address is the same, then don't bother even updating it and mark the even as successful.  If it isn't the same log a "Throttled - IP mismatch" or something and then wait out whatever the configured delay is.

I first dismissed this because querying CF in and of itself is an API call and so if you had an abuser or misbehaving script, performing the query first might still create excessive API calls.  That said, it looks like the API limit is 1200/5 minutes.  That seems very unlikely to me hit.  Putting in just a 500ms sleep in the script would ensure this could never happen.  Of course, you wouldn't want your script firing off every 3 seconds, but at least you wouldn't hit the rate limits.

But someone else on the SNBForums threw out my idea again, but instead of querying the IP over the CF API their initial suggesting was checking the last successful attempt in the log file.  You could also do some type of name resolution (ping, nslookup) to see what the address is currently resolving to and if that does not match the new IP do the updated.  If it does match, then no need to update and call the process successful/complete.

I think this is overall good design, the question would be exactly how to implement it best in terms of what to rely on, where should the excess processing go in case of failure (err for more network queries to CF even if TOS is under?  aim for open/closed fail, etc).

Anyway, if interested, we can discuss the optimal behavior and I can take a crack at coding it if you don't have the bandwidth.

Let me know.

**Comment by ulygit** [comment] 2023-04-08 21:42
Of the options you suggested, my preferred approach would be the nslookup route. Checking logs is error-prone. Querying the CF API is just silly -- you might as well simply remove the throttling check in that case.

Have you tried lowering the throttling threshold to 1? It looks like that should eliminate or substantially reduce the throttling entries. I suppose now's the time to ask why you're concerned with this at all. Is it a desire to keep clean and efficient logs? Are you getting overwhelmed with SNMP or similar alerts?

I'm not inclined to incorporate any of these changes into the script for a few reasons:

- It's the responsibility of merlin to determine when an update is necessary, and the script shouldn't try to outsmart it if it can be avoided. Better to approach merlin with a bug report and have them evaluate.
- While I do see unnecessary updates in my logging, I don't encounter anywhere near the misbehavior your logs show, and I haven't heard similar complaints from others. Obviously your ISP's leasing protocol is a contributing factor.
- There is a reasonable mitigation already in place via the throttling threshold. It may not eliminate the noisy logging but it should reduce it and any alerting you maybe receiving.

**Comment by bengalih** [comment] 2023-04-09 01:01
So let me start off by saying, yeah...it's a first world problem.  I not exceptionally worried about it - as it is with the throttle down the issue will probably be fine.  I just changed it yesterday and strangely enough I don't see a single instance of a failed, double update or watchdog restart.  I don't see how it is possible that changing the throttle would have changed that, as the best it would have done is simply made it not get into a throttle loop, but still would expect to see a double entry at some point.  I don't see a single one in the past 20 hours or so which I think has been a bit atypical.

Any issue I have would definitely be exacerbated because my lease time is only 60 minutes, so even though my IP doesn't change, my dhcp client has to do a renewal every 30 minutes.  Compared to someone with a 14 or 12 hour lease period this means dozens more times of the client running every day, which would definitely bring out any issues more than someone in the other scenario.

In short, I agree that as the script stands, it works, and perhaps it isn't worth spending time on it to fix or optimize.  That being said, I'll play devils advocate to the idea and some of your points:

1) 99% sure that the dhcp/ddns client is not Merlin code, but from Asus.  It might be an area that is open-sourced, but I suspect that isn't an area that he would consider changing.  The ddns-client kicks off every time a lease is renewed and it doesn't do any verification.  I could argue (as I will below) that Asus coded it poorly, and it isn't Merlin's problem to fix, and that is what the idea of custom scripts are for.  TBH, out of the plethora of ddns services out there, clients, etc, I'm not actually sure how many of them implement an update logic.   Most that I have played with in the past simply update on an interval or probably check every few seconds for a change and then trigger an update.  Overall, I think that if you can detect a WAN IP change (of which a renewal is one way), that's a pretty good indicator to at least start the update process.

2) I just approach this as...if you were doing this from scratch, would you do it differently?  Does it make sense to do what I'm proposing?  Do you fundamentally disagree with the concept?  Or do you think that, yeah...probably if we wanted to talk about code/operations optimization and removing potentials for failure (more below), it probably _is_ a good idea.  But, even thinking that saying "But it works...and it works well enough, just not worth the time and effort?"

I certainly respect the latter approach.  It's your project and if you just don't see it worth the effort I can't totally disagree.  While it doesn't have what I would consider an "optimal" workflow, for the time/effort involved it does the job.  So, if you have no interest, cool.  I might just hack my own script, fork yours, or maybe I just forget about this in a few days and move on :)

If you think it is a fundamentally good idea, but just don't want the bother -  I still might be interested in your input/ideas on best implementation to do a method like this.

And, because I forgot to address it above in a good spot...re: optimizations....
I definitely thing the idea of checking if a change is needed before making a push of the same data is good methodology/code.
Any change (even if it is just overwriting data) _always_ brings the potential of an issue more than no change.  That's just fundamental.  I agree, its very unlikely that something would occur that made this dangerous in this particular script, but its still the case.
Also, when we talk about network optimization.  Let's say that the average person has 4 updates per day, and most of those people their IP actually only changes weekly.  That's 27 superfluous writes to the CF database that are unnecessary.  Multiplied by everyone doing the updates.  Of course those numbers are pretty low, and therefore meaningless, but if they were 1,000,000 times they would be an issue.  So that's just scale, and you would want to resolve.  Doesn't mean that when it is smaller scale it is still the best way to handle it, it's just easier not to.

Anyway that's where all this is coming from.  In the end its no biggie, more of a thought exercise of "what might you change if you did it over" with the possibility it actually becomes an actual coding exercise (and least on my side).

**Comment by ulygit** [comment] 2023-04-09 05:05
If I were rewriting from scratch, I still wouldn't implement the check you suggest. From a design standpoint, the place for that check is in the calling code, whether it's merlin's or asus' is immaterial. Otherwise, scripts for every ddns service would be duplicating this check, and that's needlessly redundant and prone to mistakes. If the situation were serious enough that we were harming the CF service, I would definitely agree to mitigate the problem via the script if that were our only practical solution. However, we're not harming CF at all. As you pointed out CF has robust tolerance capable of handling much more than the script (throttled as it is) can dish out.

Importantly, while I agree "changing" data needlessly entails risk, changing code also entails risk. We would be adding logic that really doesn't belong in the script so that it sometimes ignores requests that it identifies as redundant and pretends to the calling code that it successfully performed an update. That's unexpected and risky behavior.

Lastly, you'll find that there are other checks and smarts that could be implemented that we don't currently do. Are we updating with a valid IP? For NAT-ed routers, should we ignore the received IP and try to determine the "correct" IP by querying a 3rd-party? Could we try to update more than once before reporting back an error? Should we parse CF responses for better logging? I had a user previously request that the script update two DNS records. We could do all those things and more.

I can appreciate your situation. If I were in your shoes, I think I'd also be uncomfortable with the amount of needless updating my router is doing. I might even be inclined to implement the kind of check you're suggesting. However, it's inappropriate in this script intended for more typical scenarios. I hope you can understand.

**Comment by bengalih** [comment] 2023-04-10 01:37
Yeah, no worries - as I said it wasn't a huge deal either way.  Even with the throttle loop happening a few times a day there was no noticeable impact except for maybe the addition of 100 lines/day of syslog entries.  I was more concerned with understanding exactly how/why the watchdog was working and causing the loop than I was with actually fixing it.

In any event, I think I might be moving off this script, although it has served me well.  In investigating the problems I discovered the following:

https://github.com/RMerl/asuswrt-merlin.ng/wiki/DDNS-services

`Starting with version 384.7, Asuswrt-Merlin uses [In-a-dyn](https://github.com/troglobit/inadyn) for DDNS updates instead of the obsolete ez-ipupdate client used until then. This client adds HTTPS support, in addition to supporting more services, and being able to easily be customized to support a lot of additional services`

Now I'm not sure how I never knew about this beforehand.  384.7 I believe came out end of 2018 - which is after I came to using your script.  It is possible that there were some issues with the earlier implementation of inadyn in regards to Cloudflare support (maybe they didn't have it?  or maybe they had some issues with API authentication like the fixes I helped you out with a few years ago).

However, now it appears to work fine for me.  I basically just needed to create an inadyn.conf file in the /jffs partition with my CF configuration and then use a single line ddns-start script (all outline in the above link).

I just tested it and it seems to work fine.  It also uses a local cache file and appears not to update if the updated entry matches the cache, so while I can't prevent the ddns-client from running every 30 minutes, it doesn't actually try to update the record if there is no change.

At this point, I don't see a compelling reason not to use it as it is more or less an in-built feature now and appears to work.  If time tells that it is problematic I might switch back.

Also, it appears to function fine using an API token scoped to only allow DNS:Edit on the particular zone I need it, so it is secure.  I read some posts about it needing more permissions, but I think changes in the CF API security might make that unnecesary.

As I was reviewing some of the CF changes, and before I decided to move to inadyn, I was looking at how to possibly improve on your script.  Based on my testing with the API as it stands now it looks like you can remove both of these from your script as user configurable settings:

`# zone information
DNS_ZONE_ID='XXXX'

# record information
DNS_RECORD_ID='XXXXX'
`
The way permissions work now you should be able to get the ZONE_ID automatically by simply parsing the domain out from the host to update.  You can also get the DNS_RECORD_ID at call time  based on the hostname instead of having to have the user configure it.

I don't know what permissions you use for your API token, nor can I remember (or recreate) how they used to work, but the way they are now you could - if you wanted - eliminate a lot of the user setup in the beginning stages of your documentation.  By just providing the host name to update and credentials, the rest could be taken care of programmatically.

Obviously, this would take some modification of the existing script to grab a few more variables, and would introduce one or two more API calls per update in order to dynamically pull this data.  However this would turn the script into much more "plug-and-play" and also require less configuration if you needed to change your host record to update, etc.

You may decide that you would rather have the user manually configure these (as you do now), or that it simply isn't worth the effort.  Again, totally your call.  If you are interested let me know and I will open up another issue to discuss how you can do this over the API.

**Comment by ulygit** [comment] 2023-04-10 02:50
I was aware of the switch to in-a-dyn back when it occurred, but I seem to recall it wasn't a solution for me in some way. It looks like CF support wasn't added until 2019, so probably that's what was lacking when I looked. Thanks for the heads up that it's a viable solution now. I'll take a look at replacing my own script with it. If it works, I'll deprecate this project and point people to in-a-dyn.

Regarding your improvement to the script, it's a good idea that I could've implemented from day one. It's tough to recall, but I imagine the effort/risk didn't seem worthwhile for what is a one-time manual process (that's reasonably documented). Parsing web responses via grep and similar is prone to errors, and I didn't want to take on the risk of getting it wrong and badly misconfiguring a user's DNS. A side benefit of this redundancy in the settings is that a user would have to get several things wrong in order to misconfigure his DNS. That said, I probably would've done it if I could count on a reliable JSON parser in the router OS.

Given your update regarding in-a-dyn, I'm even less inclined to touch the script. Likely its most valuable "feature" now is that it's already installed and working for some people. The worst thing I could do is to destabilize it!

I very much appreciate your interest and willingness to help improve this script over the years. 🙏🏼

**Comment by bengalih** [comment] 2023-04-10 15:32
Sounds good.  If you want to keep this open until you've had a chance to report back when you've had the time to tinker with inadyn.  I can offer some guidance on what I did if for some reason you can't seem to get it going.

Otherwise, we can close this down and move on.

**Comment by ulygit** [comment] 2023-04-10 17:45
I've pointed folks to In-a-dyn already. I'll go ahead and close this since the subject of the ticket is out of the script's purview.

**Closed** 2023-04-10 17:46 UTC
